import sys
from redis.commands.search.field import TextField, VectorField
from redis.commands.search.indexDefinition import IndexDefinition, IndexType
from app.cache import redis_client

INDEX_NAME = "llm_semantic_cache"

async def init_vector_index():
    """
    Connects to Redis Stack at boot and ensures our vector search index 
    schema is fully configured and active.
    """
    try:
        # 1. Check if the index already exists from a previous server boot
        await redis_client.ft(INDEX_NAME).info()
        print("📊 Redis vector index already exists. Skipping initialization.")
    except Exception:
        # If .info() throws an exception, it means the index doesn't exist yet!
        print("🏗️ Creating fresh Redis vector index schema...")
        
        # 2. Define our database structure schema
        schema = (
            TextField("$.prompt", as_name="prompt"),      # Stores the raw text question
            TextField("$.response", as_name="response"),  # Stores the raw AI answer
            VectorField(
                "$.embedding",                            # The JSON path to our coordinate array
                "FLAT",                                   # The search algorithm (FLAT is perfect for smaller caches)
                {
                    "TYPE": "FLOAT32",                    # Data type for vector numbers
                    "DIM": 1536,                          # Number of dimensions generated by OpenAI's model
                    "DISTANCE_METRIC": "COSINE"           # Math algorithm used to check how close angles are
                },
                as_name="embedding"
            )
        )
        
        # 3. Register the index layout inside Redis Stack
        await redis_client.ft(INDEX_NAME).create_index(
            fields=schema,
            definition=IndexDefinition(prefix=["semantic:"], index_type=IndexType.JSON)
        )
        print("✅ Redis vector index successfully initialized!")